SELECT TOP (1000) [Concat]
      ,[Numero]
      ,[Data_Fiscal]
      ,[NF]
      ,[Item]
      ,[Item_NF]
      ,[Material]
      ,[NCM]
      ,[Descricao]
      ,[Chave_de_Acesso]
      ,[CPF_CGC_PF_PJ]
      ,[Razao_Social_da_Pessoal_PF_PJ]
      ,[Valor_Contabil]
      ,[Aliquota]
      ,[Valor_Contabil_Sem_Imposto]
      ,[Qtd_Entrada]
      ,[UnidadeDeMedida]
      ,[Preco_Liquido_Sem_Imposto]
      ,[Pais]
      ,[CST_ICMS]
      ,[Aliquota_ICMS]
      ,[Aliquota_IPI]
      ,[Aliquota_PIS]
      ,[Aliquota_COFINS]
      ,[Movimento]
      ,[Categoria_NF]
      ,[Moeda]
      ,[Qtd_Restante]
      ,[Valor_Contabil_Restante]
  FROM [Bnds].[dbo].[Notas_Fiscais02]


 -- truncate table [Bnds].[dbo].[Notas_Fiscais02]
